INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('1', 'b', 'es la primera etapa de Ci/Cd');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('2', 'c', 'es la que se comunica con la bd');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('3', 'd', 'estan preguntando por el pilar aspectos de scrum');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('4', 'b', 'corresponde a la continius delyveri');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('5', 'c', 'considero que es maping');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('6', 'c', 'por que hablan de mapear');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('7', 'a', 'considero que es elasticidad por que permite agrandar y pequeñar los recuersos que se necesitan en la nube');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('8', 'd', 'es sprint');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('9', 'b', 'p');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('10', 'b', 'completa las etapas de ci/cd');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('11', 'd', 'es backlog');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('12', 'd', 'preguntan por el pilar de principios');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('13', 'b', 'es devods');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('14', 'b', 'p');
INSERT INTO JOSE_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('15', 'c', 'p');


